apiVersion: ppfbanka.cz/v1alpha1
kind: Project
metadata:
  name: sandbox2
spec:
  displayName: SANDBOX Two
  IDMTest: true
  environments:
    - name: uat
    - name: sit
  resources:
    hard:
      requests.cpu: 4
      requests.memory: 16Gi
      limits.cpu: 8
      limits.memory: 32Gi