apiVersion: ppfbanka.cz/v1alpha1
kind: Project
metadata:
  name: sandbox1
spec:
  displayName: SANDBOX One
  IDMTest: true
  gitRepo: https://github.com/cfy-k8s-lab/sandbox1.git
  environments:
    - name: uat
    - name: sit
  resources:
    hard:
      requests.cpu: 4
      requests.memory: 16Gi
      limits.cpu: 8
      limits.memory: 32Gi