name: PR Ruleset and Auto-Merge

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate PR Title
      id: validate_title
      run: |
        if [[ "${{ github.event.pull_request.title }}" =~ ^[A-Z]{2,}-[0-9]+: ]]; then
          echo "PR title is valid"
          echo "::set-output name=title-valid::true"
        else
          echo "PR title is invalid"
          echo "::set-output name=title-valid::false"
        fi

    - name: Validate PR Description
      id: validate_description
      run: |
        if [[ -n "${{ github.event.pull_request.body }}" ]]; then
          echo "PR description is valid"
          echo "::set-output name=description-valid::true"
        else
          echo "PR description is invalid"
          echo "::set-output name=description-valid::false"
        fi

    - name: Check All Conditions
      id: check_conditions
      run: |
        if [[ "${{ steps.validate_title.outputs.title-valid }}" == "true" && "${{ steps.validate_description.outputs.description-valid }}" == "true" ]]; then
          echo "::set-output name=all-valid::true"
        else
          echo "::set-output name=all-valid::false"
        fi

    - name: Auto Merge PR
      if: steps.check_conditions.outputs.all-valid == 'true'
      uses: davideviolante/pr-automerge-action@v1.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        merge-method: 'squash' # Default 'squash'
        min-approvals: 2 # Default 2
        base-ref: 'dev' # Default 'dev'
