name: PR Ruleset and Auto-Merge

on:
  pull_request_review:
    types:
      - submitted
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review
  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false
      review:
        description: Review ID
        required: false

jobs:
  check-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate PR Title
      id: validate_title
      run: |
        if [[ "${{ github.event.pull_request.title }}" =~ ^:robot:\ \[backstage-bot\]\ Onboarding\ new\ project ]]; then
          echo "PR title is valid"
          echo "title-valid=true" >> $GITHUB_OUTPUT
        else
          echo "PR title is invalid"
          echo "title-valid=false" >> $GITHUB_OUTPUT
        fi

    - name: Validate PR Description
      id: validate_description
      run: |
        if [[ -n "${{ github.event.pull_request.body }}" ]]; then
          echo "PR description is valid"
          echo "description-valid=true" >> $GITHUB_OUTPUT
        else
          echo "PR description is invalid"
          echo "description-valid=false" >> $GITHUB_OUTPUT
        fi

    - name: Check All Conditions
      id: check_conditions
      run: |
        if [[ "${{ steps.validate_title.outputs.title-valid }}" == "true" && "${{ steps.validate_description.outputs.description-valid }}" == "true" ]]; then
          echo "all-valid=true" >> $GITHUB_OUTPUT
        else
          echo "all-valid=false" >> $GITHUB_OUTPUT
        fi

    - name: Auto Merge PR
      if: steps.check_conditions.outputs.all-valid == 'true'
      uses: "pascalgn/automerge-action@v0.16.3"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
        MERGE_METHOD: "squash"
        MERGE_REQUIRED_APPROVALS: 0
        MERGE_DELETE_BRANCH: "true"